music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="detail"),
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User


class Album(models.Model):
    artist = models.CharField(max_length=150)
    album_title = models.CharField(max_length=150)
    genre = models.CharField(max_length=100)
    album_cover = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music/detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=150)
    is_favorite = models.BooleanField(default=False)
    audio_file = models.FileField(default='', blank=True)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from .models import Album
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = "music/index.html"

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = "music/detail.html"


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_cover']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_cover']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # creates form object without saving it to
            # database storing it locally
            user = form.save(commit=False)

            # cleaned normalized data (properly formatted)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        render(request,self.template_name,{'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add Album{% endblock %}


{% block body %}
    <div class="jumbotron" style="background-color: white">
    <h2>Add new album</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'music/form-template.html' %}
        <div class="col sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}SpaceM{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'music:index' %}">SpaceM</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:index' %}"><i class="fa fa-folder-o" aria-hidden="true"></i>&nbsp;Albums</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-music" aria-hidden="true"></i>&nbsp;Songs</a>
            </li>
        </ul>

        <form class="form-inline mr-auto" role="search" method="get" action="#">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:album-add' %}"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Add Album</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container-fluid">
{% block body %}
{% endblock %}
</div>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
      integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/d671706969.js"></script>
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album{% endblock %}

{% block body %}
    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="card-deck">
                <div class="card">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_cover %}
                            <img class="card-img-top" src="{{ album.album_cover }}">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <h2>{{ album.album_title }}</h2>
                        <h3>{{ album.artist }}</h3>
                        <h6 class="card-subtitle text-muted">{{ album.genre }}</h6>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <!-- <li role="presentation"><a href="{/% url 'music:create_song' album.id %}">Add New Song</a></li> -->

            <div class="jumbotron" style="background-color: white">

                <h3>All Songs</h3>

                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}

                <table class="table">
                    <thead>
                    <tr>
                        <th>Title</th>
                        <th>Audio File</th>
                        <th>Favorite</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for song in album.song_set.all %}
                        <tr>
                            <td>{{ song.song_title }}</td>
                            <td>
                                <a target="_blank"> <!--href="{ song.audio_file.url }}"-->
                                    <button type="button" class="btn btn-success btn-xs">
                                        <i class="fa fa-play-circle-o" aria-hidden="true"></i>&nbsp; Play
                                    </button>
                                </a>
                            </td>
                            <td>
                                <a> <!-- href="{/% url 'music:favorite' song.id %}" --><span
                                        {% if song.is_favorite %}active{% endif %}"></span></a>
                                <i class="fa fa-star" style="color:#cc1111" aria-hidden="true"></i>
                            </td>
                            <td>
                                <form method="post" style="display: inline;">
                                    <!--action="{/% url 'music:delete_song' album.id song.id %}" -->
                                    {% csrf_token %}
                                    <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                    <button type="submit" class="btn btn-danger btn-xs">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>&nbsp; Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>


    </div>

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
        <div class="form-group row ml-2 mt-3">
                <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
              <div class="col-sm-2 form-control">{{ field }}</div>
                    <div class="col-sm-offset-2 col-sm-2">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}
    <div class="albums-container container-fluid">

        <!-- Albums -->
        <div class="row">
            <div class="card-deck">
                {% for album in object_list %}
                    <div class="card" style="width: 20rem;">
                        <img class="card-img-top" src="{{ album.album_cover }}">
                        <div class="card-body">
                            <h4>{{ album.album_title }}</h4>
                            <h6>{{ album.artist }}</h6>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm"
                               role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post"
                                  style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}


{% block body %}
    <div class="jumbotron" style="background-color: white">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'music/form-template.html' %}
            <div class="col sm-10 col-sm-offset-2">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}